package com.election.backendjava.entities;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Entity class representing a reply to a post in the system.
 * This class is mapped to the "Reply" table in the database using Hibernate.
 */
@Entity
@Table(name = "reply")
public class Reply {

    /**
     * The unique ID of the reply, automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The body of the reply.
     */
    @Column(name = "body", nullable = false)
    @NotBlank(message = "Reply must be provided with a body")
    private String body;

    /**
     * The post that the reply is associated with.
     */
    @ManyToOne
    @JoinColumn(name = "postId", referencedColumnName = "id")
    private Post postId;

    /**
     * The user who created the reply.
     */
    @ManyToOne
    @JoinColumn(name = "userId", referencedColumnName = "id")
    private User userId;

    /**
     * The date and time the reply was created.
     */
    @Column(name = "date", nullable = false)
    @CreationTimestamp
    private LocalDateTime dateTime;

    // Constructors
    /**
     * Default constructor for the reply.
     */
    public Reply(){}

    /**
     * Constructor for the reply with a post, user, and body.
     * @param postId The post that the reply is associated with.
     * @param userId The user who created the reply.
     * @param body The body of the reply.
     */
    public Reply(Post postId, User userId, String body){
        this.postId = postId;
        this.userId = userId;
        this.body = body;
        this.dateTime = LocalDateTime.now();
    }

    // Getter en Setter
    /**
     * Gets the unique ID of the reply.
     *
     * @return the reply ID
     */
    public int getId(){
        return id;
    }

    /**
     * Gets the body of the reply.
     *
     * @return the reply body
     */
    public String getBody(){
        return body;
    }

    /**
     * Sets the body of the reply.
     *
     * @param body the reply body to set
     */
    public void setBody(String body){
        this.body = body;
    }

    /**
     * Gets the post that the reply is associated with.
     *
     * @return the post ID
     */
    public Post getPostId(){
        return postId;
    }

    /**
     * Gets the user who created the reply.
     *
     * @return the user ID
     */
    public User getUserId(){
        return userId;
    }

    /**
     * Gets the date and time the reply was created.
     *
     * @return the date and time of the reply
     */
    public LocalDateTime getDateTime(){
        return dateTime;
    }


}
